### ISSUE TITLE
Will Not Install

### ISSUE THREAD

**Issue by KitchM** [achorein/silenteye#32]
Am using Xubuntu 14.04.5.  Have attempted to install by this method in terminal window:

> ls silent*
silenteye-0.4.1-ubuntu.run

>  chmod -x silenteye-0.4.1-ubuntu.run

> ./silenteye-0.4.1-ubuntu.run
> bash: ./silenteye-0.4.1-ubuntu.run: Permission denied

> sudo ./silenteye-0.4.1-ubuntu.run
> sudo:  ./silenteye-0.4.1-ubuntu.run: command not found

What happened?

**Comment by KitchM** [comment]
Has anyone tried to install this program on Ubuntu?  On anything else?

**Comment by danarmstrong** [comment]
The chmod -x is making the run file non-executable. Try issuing

```
chmod +x silenteye-0.4.1-ubuntu.run
```

Then you should be able to execute the file.

**Comment by KitchM** [comment]
Thanks.  I totally missed that operand.  I checked with the file permissions and it is marked executable for me.

However, ./silenteye-0.4.1-ubuntu.run returned:
bash: ./silenteye-0.4.1-ubuntu.run: No such file or directory

And sudo ./silenteye-0.4.1-ubuntu.run returned:
sudo: unable to execute ./silenteye-0.4.1-ubuntu.run: No such file or directory

Maybe I'm in too much of a hurry, but I still can't see the mistake.

**Comment by danarmstrong** [comment]
Where did you obtain the run file from? Just quickly scanning through the repository didn't lead me to it.

Nevermind, I found it.

**Comment by danarmstrong** [comment]
When I am home tonight, I will try running this file, but looking over the open issue here is giving some doubts as to how useful it will be (namely the fact that it doesn't decode). As it is pretty clear that you are really looking for a working stego solution, have you tried steghide? It should be available via

```
sudo apt-get install steghide
```

**Comment by KitchM** [comment]
https://sourceforge.net/p/silenteye/wiki/Home/

Steghide appeared to be CLI and I want GUI.

**Comment by dcjones21** [comment]
I've installed it in Linux Mint 17.1 (ubuntu 14) with:
```
cd ~/Downloads/ 
sudo chmod +x silenteye-0.4.2.beta-ubuntu-12.04.run 
sudo ./silenteye-0.4.2.beta-ubuntu-12.04.run
```

You may need to go back and sudo your chmod

**Comment by KitchM** [comment]
Thank you dcjones21.  However, since it appears to be a CLI-base program, I probably will not pursue it any further.

Thanks again.

**Comment by dcjones21** [comment]
SilentEye is not command line, it's a full GUI.

**Comment by achorein** [comment]
SilentEye can be use in command line only if you build the branch 0.4, but is experimental. You can read the https://github.com/achorein/silenteye/tree/0.4/vagrant/prov scripts to build your own, or use the vagrant file for easy integration.

I also update links on README for download.
