### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by noplanman** [achorein/silenteye#33]
Is this project still alive?

If not, is there any other project you can recommend that does a similar job?

**Comment by achorein** [comment]
Sorry, this project is alive anymore. 
If anyone want to contribute, you are welcome.

**Comment by achorein** [comment]
@noplanman you can try steghide which is a great one

**Comment by noplanman** [comment]
@achorein Thanks for your reply. Steghide kind of seems to be dead too though 😕
